<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20210604161246 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP INDEX IDX_AB912789A76ED395');
        $this->addSql('CREATE TEMPORARY TABLE __temp__Cart AS SELECT id, user_id, reference, full_name, delivery_address, is_paid, more_informations, created_at, quantity, sub_total_ht, taxe, sub_total_ttc FROM Cart');
        $this->addSql('DROP TABLE Cart');
        $this->addSql('CREATE TABLE Cart (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, user_id INTEGER NOT NULL, reference VARCHAR(255) NOT NULL COLLATE BINARY, full_name VARCHAR(255) NOT NULL COLLATE BINARY, delivery_address CLOB NOT NULL COLLATE BINARY, is_paid BOOLEAN NOT NULL, more_informations CLOB DEFAULT NULL COLLATE BINARY, created_at DATETIME NOT NULL, quantity INTEGER NOT NULL, sub_total_ht DOUBLE PRECISION NOT NULL, taxe DOUBLE PRECISION NOT NULL, sub_total_ttc DOUBLE PRECISION NOT NULL, CONSTRAINT FK_AB912789A76ED395 FOREIGN KEY (user_id) REFERENCES user (id) NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO Cart (id, user_id, reference, full_name, delivery_address, is_paid, more_informations, created_at, quantity, sub_total_ht, taxe, sub_total_ttc) SELECT id, user_id, reference, full_name, delivery_address, is_paid, more_informations, created_at, quantity, sub_total_ht, taxe, sub_total_ttc FROM __temp__Cart');
        $this->addSql('DROP TABLE __temp__Cart');
        $this->addSql('CREATE INDEX IDX_AB912789A76ED395 ON Cart (user_id)');
        $this->addSql('DROP INDEX IDX_D4E6F81A76ED395');
        $this->addSql('CREATE TEMPORARY TABLE __temp__address AS SELECT id, user_id, full_name, campany, address, complement, phone, city, code_postal, contry FROM address');
        $this->addSql('DROP TABLE address');
        $this->addSql('CREATE TABLE address (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, user_id INTEGER NOT NULL, full_name VARCHAR(255) NOT NULL COLLATE BINARY, campany VARCHAR(255) DEFAULT NULL COLLATE BINARY, address CLOB NOT NULL COLLATE BINARY, complement CLOB DEFAULT NULL COLLATE BINARY, phone INTEGER NOT NULL, city VARCHAR(255) NOT NULL COLLATE BINARY, code_postal INTEGER NOT NULL, contry VARCHAR(255) NOT NULL COLLATE BINARY, CONSTRAINT FK_D4E6F81A76ED395 FOREIGN KEY (user_id) REFERENCES user (id) NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO address (id, user_id, full_name, campany, address, complement, phone, city, code_postal, contry) SELECT id, user_id, full_name, campany, address, complement, phone, city, code_postal, contry FROM __temp__address');
        $this->addSql('DROP TABLE __temp__address');
        $this->addSql('CREATE INDEX IDX_D4E6F81A76ED395 ON address (user_id)');
        $this->addSql('DROP INDEX IDX_229E02CCC4661F');
        $this->addSql('DROP INDEX IDX_229E024839DDBC');
        $this->addSql('CREATE TEMPORARY TABLE __temp__agence_location_voitures_voitures AS SELECT agence_location_voitures_id, voitures_id FROM agence_location_voitures_voitures');
        $this->addSql('DROP TABLE agence_location_voitures_voitures');
        $this->addSql('CREATE TABLE agence_location_voitures_voitures (agence_location_voitures_id INTEGER NOT NULL, voitures_id INTEGER NOT NULL, PRIMARY KEY(agence_location_voitures_id, voitures_id), CONSTRAINT FK_229E024839DDBC FOREIGN KEY (agence_location_voitures_id) REFERENCES agence_location_voitures (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_229E02CCC4661F FOREIGN KEY (voitures_id) REFERENCES voitures (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO agence_location_voitures_voitures (agence_location_voitures_id, voitures_id) SELECT agence_location_voitures_id, voitures_id FROM __temp__agence_location_voitures_voitures');
        $this->addSql('DROP TABLE __temp__agence_location_voitures_voitures');
        $this->addSql('CREATE INDEX IDX_229E02CCC4661F ON agence_location_voitures_voitures (voitures_id)');
        $this->addSql('CREATE INDEX IDX_229E024839DDBC ON agence_location_voitures_voitures (agence_location_voitures_id)');
        $this->addSql('DROP INDEX IDX_7C7EE068912C90D4');
        $this->addSql('DROP INDEX IDX_7C7EE0684839DDBC');
        $this->addSql('CREATE TEMPORARY TABLE __temp__agence_location_voitures_destinations AS SELECT agence_location_voitures_id, destinations_id FROM agence_location_voitures_destinations');
        $this->addSql('DROP TABLE agence_location_voitures_destinations');
        $this->addSql('CREATE TABLE agence_location_voitures_destinations (agence_location_voitures_id INTEGER NOT NULL, destinations_id INTEGER NOT NULL, PRIMARY KEY(agence_location_voitures_id, destinations_id), CONSTRAINT FK_7C7EE0684839DDBC FOREIGN KEY (agence_location_voitures_id) REFERENCES agence_location_voitures (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_7C7EE068912C90D4 FOREIGN KEY (destinations_id) REFERENCES destinations (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO agence_location_voitures_destinations (agence_location_voitures_id, destinations_id) SELECT agence_location_voitures_id, destinations_id FROM __temp__agence_location_voitures_destinations');
        $this->addSql('DROP TABLE __temp__agence_location_voitures_destinations');
        $this->addSql('CREATE INDEX IDX_7C7EE068912C90D4 ON agence_location_voitures_destinations (destinations_id)');
        $this->addSql('CREATE INDEX IDX_7C7EE0684839DDBC ON agence_location_voitures_destinations (agence_location_voitures_id)');
        $this->addSql('DROP INDEX IDX_89FCC38DBCB5C6F5');
        $this->addSql('CREATE TEMPORARY TABLE __temp__cart_details AS SELECT id, carts_id, product_name, product_price, quantity, sub_total_ht, taxe, sub_total_ttc FROM cart_details');
        $this->addSql('DROP TABLE cart_details');
        $this->addSql('CREATE TABLE cart_details (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, carts_id INTEGER NOT NULL, product_name VARCHAR(255) NOT NULL COLLATE BINARY, product_price DOUBLE PRECISION NOT NULL, quantity INTEGER NOT NULL, sub_total_ht DOUBLE PRECISION NOT NULL, taxe DOUBLE PRECISION NOT NULL, sub_total_ttc DOUBLE PRECISION NOT NULL, CONSTRAINT FK_89FCC38DBCB5C6F5 FOREIGN KEY (carts_id) REFERENCES "Cart" (id) NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO cart_details (id, carts_id, product_name, product_price, quantity, sub_total_ht, taxe, sub_total_ttc) SELECT id, carts_id, product_name, product_price, quantity, sub_total_ht, taxe, sub_total_ttc FROM __temp__cart_details');
        $this->addSql('DROP TABLE __temp__cart_details');
        $this->addSql('CREATE INDEX IDX_89FCC38DBCB5C6F5 ON cart_details (carts_id)');
        $this->addSql('DROP INDEX IDX_14EC86B2912C90D4');
        $this->addSql('DROP INDEX IDX_14EC86B2F42F66C8');
        $this->addSql('CREATE TEMPORARY TABLE __temp__hotels_destinations AS SELECT hotels_id, destinations_id FROM hotels_destinations');
        $this->addSql('DROP TABLE hotels_destinations');
        $this->addSql('CREATE TABLE hotels_destinations (hotels_id INTEGER NOT NULL, destinations_id INTEGER NOT NULL, PRIMARY KEY(hotels_id, destinations_id), CONSTRAINT FK_14EC86B2F42F66C8 FOREIGN KEY (hotels_id) REFERENCES hotels (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_14EC86B2912C90D4 FOREIGN KEY (destinations_id) REFERENCES destinations (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO hotels_destinations (hotels_id, destinations_id) SELECT hotels_id, destinations_id FROM __temp__hotels_destinations');
        $this->addSql('DROP TABLE __temp__hotels_destinations');
        $this->addSql('CREATE INDEX IDX_14EC86B2912C90D4 ON hotels_destinations (destinations_id)');
        $this->addSql('CREATE INDEX IDX_14EC86B2F42F66C8 ON hotels_destinations (hotels_id)');
        $this->addSql('DROP INDEX IDX_F5299398A76ED395');
        $this->addSql('CREATE TEMPORARY TABLE __temp__order AS SELECT id, user_id, reference, full_name, delivery_address, is_paid, more_informations, created_at, quantity, sub_total_ht, taxe, sub_total_ttc FROM "order"');
        $this->addSql('DROP TABLE "order"');
        $this->addSql('CREATE TABLE "order" (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, user_id INTEGER NOT NULL, reference VARCHAR(255) NOT NULL COLLATE BINARY, full_name VARCHAR(255) NOT NULL COLLATE BINARY, delivery_address CLOB NOT NULL COLLATE BINARY, is_paid BOOLEAN NOT NULL, more_informations CLOB DEFAULT NULL COLLATE BINARY, created_at DATETIME NOT NULL, quantity INTEGER NOT NULL, sub_total_ht DOUBLE PRECISION NOT NULL, taxe DOUBLE PRECISION NOT NULL, sub_total_ttc DOUBLE PRECISION NOT NULL, CONSTRAINT FK_F5299398A76ED395 FOREIGN KEY (user_id) REFERENCES user (id) NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO "order" (id, user_id, reference, full_name, delivery_address, is_paid, more_informations, created_at, quantity, sub_total_ht, taxe, sub_total_ttc) SELECT id, user_id, reference, full_name, delivery_address, is_paid, more_informations, created_at, quantity, sub_total_ht, taxe, sub_total_ttc FROM __temp__order');
        $this->addSql('DROP TABLE __temp__order');
        $this->addSql('CREATE INDEX IDX_F5299398A76ED395 ON "order" (user_id)');
        $this->addSql('DROP INDEX IDX_845CA2C1CFFE9AD6');
        $this->addSql('CREATE TEMPORARY TABLE __temp__order_details AS SELECT id, orders_id, product_name, product_price, quantity, sub_total_ht, taxe, sub_total_ttc FROM order_details');
        $this->addSql('DROP TABLE order_details');
        $this->addSql('CREATE TABLE order_details (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, orders_id INTEGER NOT NULL, product_name VARCHAR(255) NOT NULL COLLATE BINARY, product_price DOUBLE PRECISION NOT NULL, quantity INTEGER NOT NULL, sub_total_ht DOUBLE PRECISION NOT NULL, taxe DOUBLE PRECISION NOT NULL, sub_total_ttc DOUBLE PRECISION NOT NULL, CONSTRAINT FK_845CA2C1CFFE9AD6 FOREIGN KEY (orders_id) REFERENCES "order" (id) NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO order_details (id, orders_id, product_name, product_price, quantity, sub_total_ht, taxe, sub_total_ttc) SELECT id, orders_id, product_name, product_price, quantity, sub_total_ht, taxe, sub_total_ttc FROM __temp__order_details');
        $this->addSql('DROP TABLE __temp__order_details');
        $this->addSql('CREATE INDEX IDX_845CA2C1CFFE9AD6 ON order_details (orders_id)');
        $this->addSql('DROP INDEX IDX_9351F1F368C9E5AF');
        $this->addSql('CREATE TEMPORARY TABLE __temp__related_voyage AS SELECT id, voyage_id FROM related_voyage');
        $this->addSql('DROP TABLE related_voyage');
        $this->addSql('CREATE TABLE related_voyage (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, voyage_id INTEGER NOT NULL, CONSTRAINT FK_9351F1F368C9E5AF FOREIGN KEY (voyage_id) REFERENCES voyages (id) NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO related_voyage (id, voyage_id) SELECT id, voyage_id FROM __temp__related_voyage');
        $this->addSql('DROP TABLE __temp__related_voyage');
        $this->addSql('CREATE INDEX IDX_9351F1F368C9E5AF ON related_voyage (voyage_id)');
        $this->addSql('DROP INDEX IDX_7CE748AA76ED395');
        $this->addSql('CREATE TEMPORARY TABLE __temp__reset_password_request AS SELECT id, user_id, selector, hashed_token, requested_at, expires_at FROM reset_password_request');
        $this->addSql('DROP TABLE reset_password_request');
        $this->addSql('CREATE TABLE reset_password_request (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, user_id INTEGER NOT NULL, selector VARCHAR(20) NOT NULL COLLATE BINARY, hashed_token VARCHAR(100) NOT NULL COLLATE BINARY, requested_at DATETIME NOT NULL --(DC2Type:datetime_immutable)
        , expires_at DATETIME NOT NULL --(DC2Type:datetime_immutable)
        , CONSTRAINT FK_7CE748AA76ED395 FOREIGN KEY (user_id) REFERENCES user (id) NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO reset_password_request (id, user_id, selector, hashed_token, requested_at, expires_at) SELECT id, user_id, selector, hashed_token, requested_at, expires_at FROM __temp__reset_password_request');
        $this->addSql('DROP TABLE __temp__reset_password_request');
        $this->addSql('CREATE INDEX IDX_7CE748AA76ED395 ON reset_password_request (user_id)');
        $this->addSql('DROP INDEX IDX_E0851D6C68C9E5AF');
        $this->addSql('DROP INDEX IDX_E0851D6CA76ED395');
        $this->addSql('CREATE TEMPORARY TABLE __temp__reviews_product AS SELECT id, user_id, voyage_id, note, comment FROM reviews_product');
        $this->addSql('DROP TABLE reviews_product');
        $this->addSql('CREATE TABLE reviews_product (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, user_id INTEGER NOT NULL, voyage_id INTEGER NOT NULL, note INTEGER NOT NULL, comment CLOB DEFAULT NULL COLLATE BINARY, CONSTRAINT FK_E0851D6CA76ED395 FOREIGN KEY (user_id) REFERENCES user (id) NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_E0851D6C68C9E5AF FOREIGN KEY (voyage_id) REFERENCES voyages (id) NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO reviews_product (id, user_id, voyage_id, note, comment) SELECT id, user_id, voyage_id, note, comment FROM __temp__reviews_product');
        $this->addSql('DROP TABLE __temp__reviews_product');
        $this->addSql('CREATE INDEX IDX_E0851D6C68C9E5AF ON reviews_product (voyage_id)');
        $this->addSql('CREATE INDEX IDX_E0851D6CA76ED395 ON reviews_product (user_id)');
        $this->addSql('DROP INDEX IDX_2CDFA86C13784AA5');
        $this->addSql('DROP INDEX IDX_2CDFA86C497832A6');
        $this->addSql('CREATE TEMPORARY TABLE __temp__vols AS SELECT id, ville_depart_id, ville_arrive_id, name FROM vols');
        $this->addSql('DROP TABLE vols');
        $this->addSql('CREATE TABLE vols (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, ville_depart_id INTEGER NOT NULL, ville_arrive_id INTEGER NOT NULL, name VARCHAR(255) NOT NULL COLLATE BINARY, CONSTRAINT FK_2CDFA86C497832A6 FOREIGN KEY (ville_depart_id) REFERENCES destinations (id) NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_2CDFA86C13784AA5 FOREIGN KEY (ville_arrive_id) REFERENCES destinations (id) NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO vols (id, ville_depart_id, ville_arrive_id, name) SELECT id, ville_depart_id, ville_arrive_id, name FROM __temp__vols');
        $this->addSql('DROP TABLE __temp__vols');
        $this->addSql('CREATE INDEX IDX_2CDFA86C13784AA5 ON vols (ville_arrive_id)');
        $this->addSql('CREATE INDEX IDX_2CDFA86C497832A6 ON vols (ville_depart_id)');
        $this->addSql('DROP INDEX IDX_BEA8033B5F9EE3CE');
        $this->addSql('DROP INDEX IDX_BEA8033B573E0EFC');
        $this->addSql('CREATE TEMPORARY TABLE __temp__vols_compagnies AS SELECT vols_id, compagnies_id FROM vols_compagnies');
        $this->addSql('DROP TABLE vols_compagnies');
        $this->addSql('CREATE TABLE vols_compagnies (vols_id INTEGER NOT NULL, compagnies_id INTEGER NOT NULL, PRIMARY KEY(vols_id, compagnies_id), CONSTRAINT FK_BEA8033B573E0EFC FOREIGN KEY (vols_id) REFERENCES vols (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_BEA8033B5F9EE3CE FOREIGN KEY (compagnies_id) REFERENCES compagnies (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO vols_compagnies (vols_id, compagnies_id) SELECT vols_id, compagnies_id FROM __temp__vols_compagnies');
        $this->addSql('DROP TABLE __temp__vols_compagnies');
        $this->addSql('CREATE INDEX IDX_BEA8033B5F9EE3CE ON vols_compagnies (compagnies_id)');
        $this->addSql('CREATE INDEX IDX_BEA8033B573E0EFC ON vols_compagnies (vols_id)');
        $this->addSql('DROP INDEX IDX_F5CB3F2B7F1F6109');
        $this->addSql('DROP INDEX IDX_F5CB3F2B573E0EFC');
        $this->addSql('CREATE TEMPORARY TABLE __temp__vols_type_vols AS SELECT vols_id, type_vols_id FROM vols_type_vols');
        $this->addSql('DROP TABLE vols_type_vols');
        $this->addSql('CREATE TABLE vols_type_vols (vols_id INTEGER NOT NULL, type_vols_id INTEGER NOT NULL, PRIMARY KEY(vols_id, type_vols_id), CONSTRAINT FK_F5CB3F2B573E0EFC FOREIGN KEY (vols_id) REFERENCES vols (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_F5CB3F2B7F1F6109 FOREIGN KEY (type_vols_id) REFERENCES type_vols (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO vols_type_vols (vols_id, type_vols_id) SELECT vols_id, type_vols_id FROM __temp__vols_type_vols');
        $this->addSql('DROP TABLE __temp__vols_type_vols');
        $this->addSql('CREATE INDEX IDX_F5CB3F2B7F1F6109 ON vols_type_vols (type_vols_id)');
        $this->addSql('CREATE INDEX IDX_F5CB3F2B573E0EFC ON vols_type_vols (vols_id)');
        $this->addSql('DROP INDEX IDX_F21C3E96912C90D4');
        $this->addSql('DROP INDEX IDX_F21C3E96A170CAB9');
        $this->addSql('CREATE TEMPORARY TABLE __temp__voyages_destinations AS SELECT voyages_id, destinations_id FROM voyages_destinations');
        $this->addSql('DROP TABLE voyages_destinations');
        $this->addSql('CREATE TABLE voyages_destinations (voyages_id INTEGER NOT NULL, destinations_id INTEGER NOT NULL, PRIMARY KEY(voyages_id, destinations_id), CONSTRAINT FK_F21C3E96A170CAB9 FOREIGN KEY (voyages_id) REFERENCES voyages (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_F21C3E96912C90D4 FOREIGN KEY (destinations_id) REFERENCES destinations (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO voyages_destinations (voyages_id, destinations_id) SELECT voyages_id, destinations_id FROM __temp__voyages_destinations');
        $this->addSql('DROP TABLE __temp__voyages_destinations');
        $this->addSql('CREATE INDEX IDX_F21C3E96912C90D4 ON voyages_destinations (destinations_id)');
        $this->addSql('CREATE INDEX IDX_F21C3E96A170CAB9 ON voyages_destinations (voyages_id)');
        $this->addSql('DROP INDEX IDX_4561FF8BF42F66C8');
        $this->addSql('DROP INDEX IDX_4561FF8BA170CAB9');
        $this->addSql('CREATE TEMPORARY TABLE __temp__voyages_hotels AS SELECT voyages_id, hotels_id FROM voyages_hotels');
        $this->addSql('DROP TABLE voyages_hotels');
        $this->addSql('CREATE TABLE voyages_hotels (voyages_id INTEGER NOT NULL, hotels_id INTEGER NOT NULL, PRIMARY KEY(voyages_id, hotels_id), CONSTRAINT FK_4561FF8BA170CAB9 FOREIGN KEY (voyages_id) REFERENCES voyages (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_4561FF8BF42F66C8 FOREIGN KEY (hotels_id) REFERENCES hotels (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO voyages_hotels (voyages_id, hotels_id) SELECT voyages_id, hotels_id FROM __temp__voyages_hotels');
        $this->addSql('DROP TABLE __temp__voyages_hotels');
        $this->addSql('CREATE INDEX IDX_4561FF8BF42F66C8 ON voyages_hotels (hotels_id)');
        $this->addSql('CREATE INDEX IDX_4561FF8BA170CAB9 ON voyages_hotels (voyages_id)');
        $this->addSql('DROP INDEX IDX_F25821CB4839DDBC');
        $this->addSql('DROP INDEX IDX_F25821CBA170CAB9');
        $this->addSql('CREATE TEMPORARY TABLE __temp__voyages_agence_location_voitures AS SELECT voyages_id, agence_location_voitures_id FROM voyages_agence_location_voitures');
        $this->addSql('DROP TABLE voyages_agence_location_voitures');
        $this->addSql('CREATE TABLE voyages_agence_location_voitures (voyages_id INTEGER NOT NULL, agence_location_voitures_id INTEGER NOT NULL, PRIMARY KEY(voyages_id, agence_location_voitures_id), CONSTRAINT FK_F25821CBA170CAB9 FOREIGN KEY (voyages_id) REFERENCES voyages (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_F25821CB4839DDBC FOREIGN KEY (agence_location_voitures_id) REFERENCES agence_location_voitures (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO voyages_agence_location_voitures (voyages_id, agence_location_voitures_id) SELECT voyages_id, agence_location_voitures_id FROM __temp__voyages_agence_location_voitures');
        $this->addSql('DROP TABLE __temp__voyages_agence_location_voitures');
        $this->addSql('CREATE INDEX IDX_F25821CB4839DDBC ON voyages_agence_location_voitures (agence_location_voitures_id)');
        $this->addSql('CREATE INDEX IDX_F25821CBA170CAB9 ON voyages_agence_location_voitures (voyages_id)');
        $this->addSql('DROP INDEX IDX_B0421D5573E0EFC');
        $this->addSql('DROP INDEX IDX_B0421D5A170CAB9');
        $this->addSql('CREATE TEMPORARY TABLE __temp__voyages_vols AS SELECT voyages_id, vols_id FROM voyages_vols');
        $this->addSql('DROP TABLE voyages_vols');
        $this->addSql('CREATE TABLE voyages_vols (voyages_id INTEGER NOT NULL, vols_id INTEGER NOT NULL, PRIMARY KEY(voyages_id, vols_id), CONSTRAINT FK_B0421D5A170CAB9 FOREIGN KEY (voyages_id) REFERENCES voyages (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_B0421D5573E0EFC FOREIGN KEY (vols_id) REFERENCES vols (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO voyages_vols (voyages_id, vols_id) SELECT voyages_id, vols_id FROM __temp__voyages_vols');
        $this->addSql('DROP TABLE __temp__voyages_vols');
        $this->addSql('CREATE INDEX IDX_B0421D5573E0EFC ON voyages_vols (vols_id)');
        $this->addSql('CREATE INDEX IDX_B0421D5A170CAB9 ON voyages_vols (voyages_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP INDEX IDX_AB912789A76ED395');
        $this->addSql('CREATE TEMPORARY TABLE __temp__Cart AS SELECT id, user_id, reference, full_name, delivery_address, is_paid, more_informations, created_at, quantity, sub_total_ht, taxe, sub_total_ttc FROM "Cart"');
        $this->addSql('DROP TABLE "Cart"');
        $this->addSql('CREATE TABLE "Cart" (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, user_id INTEGER NOT NULL, reference VARCHAR(255) NOT NULL, full_name VARCHAR(255) NOT NULL, delivery_address CLOB NOT NULL, is_paid BOOLEAN NOT NULL, more_informations CLOB DEFAULT NULL, created_at DATETIME NOT NULL, quantity INTEGER NOT NULL, sub_total_ht DOUBLE PRECISION NOT NULL, taxe DOUBLE PRECISION NOT NULL, sub_total_ttc DOUBLE PRECISION NOT NULL)');
        $this->addSql('INSERT INTO "Cart" (id, user_id, reference, full_name, delivery_address, is_paid, more_informations, created_at, quantity, sub_total_ht, taxe, sub_total_ttc) SELECT id, user_id, reference, full_name, delivery_address, is_paid, more_informations, created_at, quantity, sub_total_ht, taxe, sub_total_ttc FROM __temp__Cart');
        $this->addSql('DROP TABLE __temp__Cart');
        $this->addSql('CREATE INDEX IDX_AB912789A76ED395 ON "Cart" (user_id)');
        $this->addSql('DROP INDEX IDX_D4E6F81A76ED395');
        $this->addSql('CREATE TEMPORARY TABLE __temp__address AS SELECT id, user_id, full_name, campany, address, complement, phone, city, code_postal, contry FROM address');
        $this->addSql('DROP TABLE address');
        $this->addSql('CREATE TABLE address (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, user_id INTEGER NOT NULL, full_name VARCHAR(255) NOT NULL, campany VARCHAR(255) DEFAULT NULL, address CLOB NOT NULL, complement CLOB DEFAULT NULL, phone INTEGER NOT NULL, city VARCHAR(255) NOT NULL, code_postal INTEGER NOT NULL, contry VARCHAR(255) NOT NULL)');
        $this->addSql('INSERT INTO address (id, user_id, full_name, campany, address, complement, phone, city, code_postal, contry) SELECT id, user_id, full_name, campany, address, complement, phone, city, code_postal, contry FROM __temp__address');
        $this->addSql('DROP TABLE __temp__address');
        $this->addSql('CREATE INDEX IDX_D4E6F81A76ED395 ON address (user_id)');
        $this->addSql('DROP INDEX IDX_7C7EE0684839DDBC');
        $this->addSql('DROP INDEX IDX_7C7EE068912C90D4');
        $this->addSql('CREATE TEMPORARY TABLE __temp__agence_location_voitures_destinations AS SELECT agence_location_voitures_id, destinations_id FROM agence_location_voitures_destinations');
        $this->addSql('DROP TABLE agence_location_voitures_destinations');
        $this->addSql('CREATE TABLE agence_location_voitures_destinations (agence_location_voitures_id INTEGER NOT NULL, destinations_id INTEGER NOT NULL, PRIMARY KEY(agence_location_voitures_id, destinations_id))');
        $this->addSql('INSERT INTO agence_location_voitures_destinations (agence_location_voitures_id, destinations_id) SELECT agence_location_voitures_id, destinations_id FROM __temp__agence_location_voitures_destinations');
        $this->addSql('DROP TABLE __temp__agence_location_voitures_destinations');
        $this->addSql('CREATE INDEX IDX_7C7EE0684839DDBC ON agence_location_voitures_destinations (agence_location_voitures_id)');
        $this->addSql('CREATE INDEX IDX_7C7EE068912C90D4 ON agence_location_voitures_destinations (destinations_id)');
        $this->addSql('DROP INDEX IDX_229E024839DDBC');
        $this->addSql('DROP INDEX IDX_229E02CCC4661F');
        $this->addSql('CREATE TEMPORARY TABLE __temp__agence_location_voitures_voitures AS SELECT agence_location_voitures_id, voitures_id FROM agence_location_voitures_voitures');
        $this->addSql('DROP TABLE agence_location_voitures_voitures');
        $this->addSql('CREATE TABLE agence_location_voitures_voitures (agence_location_voitures_id INTEGER NOT NULL, voitures_id INTEGER NOT NULL, PRIMARY KEY(agence_location_voitures_id, voitures_id))');
        $this->addSql('INSERT INTO agence_location_voitures_voitures (agence_location_voitures_id, voitures_id) SELECT agence_location_voitures_id, voitures_id FROM __temp__agence_location_voitures_voitures');
        $this->addSql('DROP TABLE __temp__agence_location_voitures_voitures');
        $this->addSql('CREATE INDEX IDX_229E024839DDBC ON agence_location_voitures_voitures (agence_location_voitures_id)');
        $this->addSql('CREATE INDEX IDX_229E02CCC4661F ON agence_location_voitures_voitures (voitures_id)');
        $this->addSql('DROP INDEX IDX_89FCC38DBCB5C6F5');
        $this->addSql('CREATE TEMPORARY TABLE __temp__cart_details AS SELECT id, carts_id, product_name, product_price, quantity, sub_total_ht, taxe, sub_total_ttc FROM cart_details');
        $this->addSql('DROP TABLE cart_details');
        $this->addSql('CREATE TABLE cart_details (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, carts_id INTEGER NOT NULL, product_name VARCHAR(255) NOT NULL, product_price DOUBLE PRECISION NOT NULL, quantity INTEGER NOT NULL, sub_total_ht DOUBLE PRECISION NOT NULL, taxe DOUBLE PRECISION NOT NULL, sub_total_ttc DOUBLE PRECISION NOT NULL)');
        $this->addSql('INSERT INTO cart_details (id, carts_id, product_name, product_price, quantity, sub_total_ht, taxe, sub_total_ttc) SELECT id, carts_id, product_name, product_price, quantity, sub_total_ht, taxe, sub_total_ttc FROM __temp__cart_details');
        $this->addSql('DROP TABLE __temp__cart_details');
        $this->addSql('CREATE INDEX IDX_89FCC38DBCB5C6F5 ON cart_details (carts_id)');
        $this->addSql('DROP INDEX IDX_14EC86B2F42F66C8');
        $this->addSql('DROP INDEX IDX_14EC86B2912C90D4');
        $this->addSql('CREATE TEMPORARY TABLE __temp__hotels_destinations AS SELECT hotels_id, destinations_id FROM hotels_destinations');
        $this->addSql('DROP TABLE hotels_destinations');
        $this->addSql('CREATE TABLE hotels_destinations (hotels_id INTEGER NOT NULL, destinations_id INTEGER NOT NULL, PRIMARY KEY(hotels_id, destinations_id))');
        $this->addSql('INSERT INTO hotels_destinations (hotels_id, destinations_id) SELECT hotels_id, destinations_id FROM __temp__hotels_destinations');
        $this->addSql('DROP TABLE __temp__hotels_destinations');
        $this->addSql('CREATE INDEX IDX_14EC86B2F42F66C8 ON hotels_destinations (hotels_id)');
        $this->addSql('CREATE INDEX IDX_14EC86B2912C90D4 ON hotels_destinations (destinations_id)');
        $this->addSql('DROP INDEX IDX_F5299398A76ED395');
        $this->addSql('CREATE TEMPORARY TABLE __temp__order AS SELECT id, user_id, reference, full_name, delivery_address, is_paid, more_informations, created_at, quantity, sub_total_ht, taxe, sub_total_ttc FROM "order"');
        $this->addSql('DROP TABLE "order"');
        $this->addSql('CREATE TABLE "order" (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, user_id INTEGER NOT NULL, reference VARCHAR(255) NOT NULL, full_name VARCHAR(255) NOT NULL, delivery_address CLOB NOT NULL, is_paid BOOLEAN NOT NULL, more_informations CLOB DEFAULT NULL, created_at DATETIME NOT NULL, quantity INTEGER NOT NULL, sub_total_ht DOUBLE PRECISION NOT NULL, taxe DOUBLE PRECISION NOT NULL, sub_total_ttc DOUBLE PRECISION NOT NULL)');
        $this->addSql('INSERT INTO "order" (id, user_id, reference, full_name, delivery_address, is_paid, more_informations, created_at, quantity, sub_total_ht, taxe, sub_total_ttc) SELECT id, user_id, reference, full_name, delivery_address, is_paid, more_informations, created_at, quantity, sub_total_ht, taxe, sub_total_ttc FROM __temp__order');
        $this->addSql('DROP TABLE __temp__order');
        $this->addSql('CREATE INDEX IDX_F5299398A76ED395 ON "order" (user_id)');
        $this->addSql('DROP INDEX IDX_845CA2C1CFFE9AD6');
        $this->addSql('CREATE TEMPORARY TABLE __temp__order_details AS SELECT id, orders_id, product_name, product_price, quantity, sub_total_ht, taxe, sub_total_ttc FROM order_details');
        $this->addSql('DROP TABLE order_details');
        $this->addSql('CREATE TABLE order_details (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, orders_id INTEGER NOT NULL, product_name VARCHAR(255) NOT NULL, product_price DOUBLE PRECISION NOT NULL, quantity INTEGER NOT NULL, sub_total_ht DOUBLE PRECISION NOT NULL, taxe DOUBLE PRECISION NOT NULL, sub_total_ttc DOUBLE PRECISION NOT NULL)');
        $this->addSql('INSERT INTO order_details (id, orders_id, product_name, product_price, quantity, sub_total_ht, taxe, sub_total_ttc) SELECT id, orders_id, product_name, product_price, quantity, sub_total_ht, taxe, sub_total_ttc FROM __temp__order_details');
        $this->addSql('DROP TABLE __temp__order_details');
        $this->addSql('CREATE INDEX IDX_845CA2C1CFFE9AD6 ON order_details (orders_id)');
        $this->addSql('DROP INDEX IDX_9351F1F368C9E5AF');
        $this->addSql('CREATE TEMPORARY TABLE __temp__related_voyage AS SELECT id, voyage_id FROM related_voyage');
        $this->addSql('DROP TABLE related_voyage');
        $this->addSql('CREATE TABLE related_voyage (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, voyage_id INTEGER NOT NULL)');
        $this->addSql('INSERT INTO related_voyage (id, voyage_id) SELECT id, voyage_id FROM __temp__related_voyage');
        $this->addSql('DROP TABLE __temp__related_voyage');
        $this->addSql('CREATE INDEX IDX_9351F1F368C9E5AF ON related_voyage (voyage_id)');
        $this->addSql('DROP INDEX IDX_7CE748AA76ED395');
        $this->addSql('CREATE TEMPORARY TABLE __temp__reset_password_request AS SELECT id, user_id, selector, hashed_token, requested_at, expires_at FROM reset_password_request');
        $this->addSql('DROP TABLE reset_password_request');
        $this->addSql('CREATE TABLE reset_password_request (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, user_id INTEGER NOT NULL, selector VARCHAR(20) NOT NULL, hashed_token VARCHAR(100) NOT NULL, requested_at DATETIME NOT NULL --(DC2Type:datetime_immutable)
        , expires_at DATETIME NOT NULL --(DC2Type:datetime_immutable)
        )');
        $this->addSql('INSERT INTO reset_password_request (id, user_id, selector, hashed_token, requested_at, expires_at) SELECT id, user_id, selector, hashed_token, requested_at, expires_at FROM __temp__reset_password_request');
        $this->addSql('DROP TABLE __temp__reset_password_request');
        $this->addSql('CREATE INDEX IDX_7CE748AA76ED395 ON reset_password_request (user_id)');
        $this->addSql('DROP INDEX IDX_E0851D6CA76ED395');
        $this->addSql('DROP INDEX IDX_E0851D6C68C9E5AF');
        $this->addSql('CREATE TEMPORARY TABLE __temp__reviews_product AS SELECT id, user_id, voyage_id, note, comment FROM reviews_product');
        $this->addSql('DROP TABLE reviews_product');
        $this->addSql('CREATE TABLE reviews_product (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, user_id INTEGER NOT NULL, voyage_id INTEGER NOT NULL, note INTEGER NOT NULL, comment CLOB DEFAULT NULL)');
        $this->addSql('INSERT INTO reviews_product (id, user_id, voyage_id, note, comment) SELECT id, user_id, voyage_id, note, comment FROM __temp__reviews_product');
        $this->addSql('DROP TABLE __temp__reviews_product');
        $this->addSql('CREATE INDEX IDX_E0851D6CA76ED395 ON reviews_product (user_id)');
        $this->addSql('CREATE INDEX IDX_E0851D6C68C9E5AF ON reviews_product (voyage_id)');
        $this->addSql('DROP INDEX IDX_2CDFA86C497832A6');
        $this->addSql('DROP INDEX IDX_2CDFA86C13784AA5');
        $this->addSql('CREATE TEMPORARY TABLE __temp__vols AS SELECT id, ville_depart_id, ville_arrive_id, name FROM vols');
        $this->addSql('DROP TABLE vols');
        $this->addSql('CREATE TABLE vols (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, ville_depart_id INTEGER NOT NULL, ville_arrive_id INTEGER NOT NULL, name VARCHAR(255) NOT NULL)');
        $this->addSql('INSERT INTO vols (id, ville_depart_id, ville_arrive_id, name) SELECT id, ville_depart_id, ville_arrive_id, name FROM __temp__vols');
        $this->addSql('DROP TABLE __temp__vols');
        $this->addSql('CREATE INDEX IDX_2CDFA86C497832A6 ON vols (ville_depart_id)');
        $this->addSql('CREATE INDEX IDX_2CDFA86C13784AA5 ON vols (ville_arrive_id)');
        $this->addSql('DROP INDEX IDX_BEA8033B573E0EFC');
        $this->addSql('DROP INDEX IDX_BEA8033B5F9EE3CE');
        $this->addSql('CREATE TEMPORARY TABLE __temp__vols_compagnies AS SELECT vols_id, compagnies_id FROM vols_compagnies');
        $this->addSql('DROP TABLE vols_compagnies');
        $this->addSql('CREATE TABLE vols_compagnies (vols_id INTEGER NOT NULL, compagnies_id INTEGER NOT NULL, PRIMARY KEY(vols_id, compagnies_id))');
        $this->addSql('INSERT INTO vols_compagnies (vols_id, compagnies_id) SELECT vols_id, compagnies_id FROM __temp__vols_compagnies');
        $this->addSql('DROP TABLE __temp__vols_compagnies');
        $this->addSql('CREATE INDEX IDX_BEA8033B573E0EFC ON vols_compagnies (vols_id)');
        $this->addSql('CREATE INDEX IDX_BEA8033B5F9EE3CE ON vols_compagnies (compagnies_id)');
        $this->addSql('DROP INDEX IDX_F5CB3F2B573E0EFC');
        $this->addSql('DROP INDEX IDX_F5CB3F2B7F1F6109');
        $this->addSql('CREATE TEMPORARY TABLE __temp__vols_type_vols AS SELECT vols_id, type_vols_id FROM vols_type_vols');
        $this->addSql('DROP TABLE vols_type_vols');
        $this->addSql('CREATE TABLE vols_type_vols (vols_id INTEGER NOT NULL, type_vols_id INTEGER NOT NULL, PRIMARY KEY(vols_id, type_vols_id))');
        $this->addSql('INSERT INTO vols_type_vols (vols_id, type_vols_id) SELECT vols_id, type_vols_id FROM __temp__vols_type_vols');
        $this->addSql('DROP TABLE __temp__vols_type_vols');
        $this->addSql('CREATE INDEX IDX_F5CB3F2B573E0EFC ON vols_type_vols (vols_id)');
        $this->addSql('CREATE INDEX IDX_F5CB3F2B7F1F6109 ON vols_type_vols (type_vols_id)');
        $this->addSql('DROP INDEX IDX_F25821CBA170CAB9');
        $this->addSql('DROP INDEX IDX_F25821CB4839DDBC');
        $this->addSql('CREATE TEMPORARY TABLE __temp__voyages_agence_location_voitures AS SELECT voyages_id, agence_location_voitures_id FROM voyages_agence_location_voitures');
        $this->addSql('DROP TABLE voyages_agence_location_voitures');
        $this->addSql('CREATE TABLE voyages_agence_location_voitures (voyages_id INTEGER NOT NULL, agence_location_voitures_id INTEGER NOT NULL, PRIMARY KEY(voyages_id, agence_location_voitures_id))');
        $this->addSql('INSERT INTO voyages_agence_location_voitures (voyages_id, agence_location_voitures_id) SELECT voyages_id, agence_location_voitures_id FROM __temp__voyages_agence_location_voitures');
        $this->addSql('DROP TABLE __temp__voyages_agence_location_voitures');
        $this->addSql('CREATE INDEX IDX_F25821CBA170CAB9 ON voyages_agence_location_voitures (voyages_id)');
        $this->addSql('CREATE INDEX IDX_F25821CB4839DDBC ON voyages_agence_location_voitures (agence_location_voitures_id)');
        $this->addSql('DROP INDEX IDX_F21C3E96A170CAB9');
        $this->addSql('DROP INDEX IDX_F21C3E96912C90D4');
        $this->addSql('CREATE TEMPORARY TABLE __temp__voyages_destinations AS SELECT voyages_id, destinations_id FROM voyages_destinations');
        $this->addSql('DROP TABLE voyages_destinations');
        $this->addSql('CREATE TABLE voyages_destinations (voyages_id INTEGER NOT NULL, destinations_id INTEGER NOT NULL, PRIMARY KEY(voyages_id, destinations_id))');
        $this->addSql('INSERT INTO voyages_destinations (voyages_id, destinations_id) SELECT voyages_id, destinations_id FROM __temp__voyages_destinations');
        $this->addSql('DROP TABLE __temp__voyages_destinations');
        $this->addSql('CREATE INDEX IDX_F21C3E96A170CAB9 ON voyages_destinations (voyages_id)');
        $this->addSql('CREATE INDEX IDX_F21C3E96912C90D4 ON voyages_destinations (destinations_id)');
        $this->addSql('DROP INDEX IDX_4561FF8BA170CAB9');
        $this->addSql('DROP INDEX IDX_4561FF8BF42F66C8');
        $this->addSql('CREATE TEMPORARY TABLE __temp__voyages_hotels AS SELECT voyages_id, hotels_id FROM voyages_hotels');
        $this->addSql('DROP TABLE voyages_hotels');
        $this->addSql('CREATE TABLE voyages_hotels (voyages_id INTEGER NOT NULL, hotels_id INTEGER NOT NULL, PRIMARY KEY(voyages_id, hotels_id))');
        $this->addSql('INSERT INTO voyages_hotels (voyages_id, hotels_id) SELECT voyages_id, hotels_id FROM __temp__voyages_hotels');
        $this->addSql('DROP TABLE __temp__voyages_hotels');
        $this->addSql('CREATE INDEX IDX_4561FF8BA170CAB9 ON voyages_hotels (voyages_id)');
        $this->addSql('CREATE INDEX IDX_4561FF8BF42F66C8 ON voyages_hotels (hotels_id)');
        $this->addSql('DROP INDEX IDX_B0421D5A170CAB9');
        $this->addSql('DROP INDEX IDX_B0421D5573E0EFC');
        $this->addSql('CREATE TEMPORARY TABLE __temp__voyages_vols AS SELECT voyages_id, vols_id FROM voyages_vols');
        $this->addSql('DROP TABLE voyages_vols');
        $this->addSql('CREATE TABLE voyages_vols (voyages_id INTEGER NOT NULL, vols_id INTEGER NOT NULL, PRIMARY KEY(voyages_id, vols_id))');
        $this->addSql('INSERT INTO voyages_vols (voyages_id, vols_id) SELECT voyages_id, vols_id FROM __temp__voyages_vols');
        $this->addSql('DROP TABLE __temp__voyages_vols');
        $this->addSql('CREATE INDEX IDX_B0421D5A170CAB9 ON voyages_vols (voyages_id)');
        $this->addSql('CREATE INDEX IDX_B0421D5573E0EFC ON voyages_vols (vols_id)');
    }
}
